resources:
- name: compliance-masonry-source
  type: git
  source:
    uri: git@github.com:geramirez/compliance-masonry.git
    branch: master
    private_key: {{github-private-key}}

jobs:
- name: Test CM on Ubuntu
  plan:
  - get: compliance-masonry-source
    trigger: true
  - task: run-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
          tag: 1.7.5-wheezy
      inputs:
      - name: compliance-masonry-source
      run:
        path: sh
        args:
        - -exc
        - |
          mkdir -p src/github.com/opencontrol/
          git clone compliance-masonry-source src/github.com/opencontrol/compliance-masonry
          cd src/github.com/opencontrol/compliance-masonry
          echo `pwd`
          go test

- name: Test CM on Alpine
  plan:
  - get: compliance-masonry-source
    trigger: true
  - task: run-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
          tag: 1.7.5-alpine3.5
      inputs:
      - name: compliance-masonry-source
      run:
        path: sh
        args:
        - -exc
        - |
          apk update
          apk add git
          mkdir -p src/github.com/opencontrol/
          git clone compliance-masonry-source src/github.com/opencontrol/compliance-masonry
          cd src/github.com/opencontrol/compliance-masonry
          go test
